add few utilities
RedHatQE/openshift-operator-utilities pull request #30
Opened 2024-04-10 20:58 UTC by dbasunag

2024-04-10 20:58 UTC, redhat-qe-bot1 commented
Report bugs in [Issues](https://github.com/myakove/github-webhook-server/issues)

The following are automatically added:
 * Add reviewers from OWNER file (in the root of the repository) under reviewers section.
 * Set PR size label.
 * New issue is created for the PR. (Closed when PR is merged/closed)
 * Run [pre-commit](https://pre-commit.ci/) if `.pre-commit-config.yaml` exists in the repo.

Available user actions:
 * To mark PR as WIP comment `/wip` to the PR, To remove it from the PR comment `/wip cancel` to the PR.
 * To block merging of PR comment `/hold`, To un-block merging of PR comment `/hold cancel`.
 * To mark PR as verified comment `/verified` to the PR, to un-verify comment `/verified cancel` to the PR.
        verified label removed on each new commit push.
 * To cherry pick a merged PR comment `/cherry-pick <target branch to cherry-pick to>` in the PR.
    * Multiple target branches can be cherry-picked, separated by spaces. (`/cherry-pick branch1 branch2`)
    * Cherry-pick will be started when PR is merged
 * To build and push container image command `/build-and-push-container` in the PR (tag will be the PR number).
 * To add a label by comment use `/<label name>`, to remove, use `/<label name> cancel`
 * To assign reviewers based on OWNERS file use `/assign-reviewers`
 * To check if PR can be merged use `/check-can-merge`

<details>
<summary>Supported /retest check runs</summary>

 * `/retest tox`: Retest tox
 * `/retest python-module-install`: Retest python-module-install

</details>

<details>
<summary>Supported labels</summary>

 * hold
 * verified
 * wip
 * lgtm

</details>

2024-04-11 06:33 UTC, jpeimer approved these changes

2024-04-11 07:01 UTC, myakove commented
Change the PR title to have a meaningful description
Add body that describe what was added in this PR.

2024-04-11 07:15 UTC, jpeimer requested changes
Please add a more meaningful title and description

2024-04-11 13:40 UTC, jpeimer submitted a review, later dismissed

2024-04-11 13:51 UTC, myakove requested changes
Please add tests, this repo does not have code (beside 1 function).

2024-04-11 13:51 UTC, myakove commented on operator_utilities/infra.py
> +from simple_logger.logger import get_logger
all functions in this file are not operators related.

2024-04-11 13:51 UTC, myakove commented on operator_utilities/operator.py
> +    gets subscription by name
not operators related functions

2024-04-11 13:51 UTC, myakove commented on operator_utilities/operator.py
> +def get_catalog_source(catalogsource_name, catalogsource_namespace):
not operators related

2024-04-11 13:51 UTC, myakove commented on operator_utilities/hyperconverged.py
> +def get_hyperconverged_resource(hyperconverged_name, namespace_name):
Please start using typing for all

2024-04-11 13:55 UTC, dbasunag commented on operator_utilities/operator.py
> +def get_catalog_source(catalogsource_name, catalogsource_namespace):
Catalogsource is part of OLM. https://olm.operatorframework.io/docs/concepts/crds/catalogsource/

2024-04-11 13:56 UTC, dbasunag commented on operator_utilities/operator.py
> +    gets subscription by name
Ditto, subscription is part of OLM

2024-04-11 13:57 UTC, dbasunag commented on operator_utilities/hyperconverged.py
> +def get_hyperconverged_resource(hyperconverged_name, namespace_name):
Ok, I will do this.

2024-04-11 14:34 UTC, dbasunag commented on operator_utilities/infra.py
> +from simple_logger.logger import get_logger
Renaming file to olm.py

2024-04-11 14:34 UTC, dbasunag commented
> Please add tests, this repo does not have code (beside 1 function).

Will do. In a follow up PR.

2024-04-15 18:49 UTC, dbasunag commented
/verified

2024-04-15 18:49 UTC, merged